name: Engram
options:
  bundleIdPrefix: dev.balakumar
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    # Swift 6 toolchain with Swift 5 language mode (matches Package.swift swiftLanguageModes: [.v5])
    # This isn't a downgrade - it's using Swift 6 compiler with Swift 5 concurrency rules
    SWIFT_VERSION: "5"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Engram Development"
    DEVELOPMENT_TEAM: ""
    LD_RUNPATH_SEARCH_PATHS:
      - "@executable_path/../Frameworks"
      - "@loader_path/../Frameworks"
      - "/usr/lib/swift"
      - "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-6.2/macosx"
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.7.0"
  SQLite.swift:
    url: https://github.com/stephencelis/SQLite.swift.git
    from: "0.15.0"
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    branch: main
  VecturaKit:
    url: https://github.com/rryam/VecturaKit.git
    from: "2.3.1"
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    branch: main

targets:
  # Core Audio Engine Framework
  AudioEngine:
    type: framework
    platform: macOS
    sources:
      - path: Sources/AudioEngine
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.balakumar.engram.audioengine
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"

  # Database Framework
  Database:
    type: framework
    platform: macOS
    sources:
      - path: Sources/Database
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.balakumar.engram.database
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - package: SQLite.swift
        product: SQLite

  # Intelligence Framework (AI/Transcription)
  Intelligence:
    type: framework
    platform: macOS
    sources:
      - path: Sources/Intelligence
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.balakumar.engram.intelligence
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - target: Database
      - package: WhisperKit
        product: WhisperKit
      - package: FluidAudio
        product: FluidAudio
      - package: VecturaKit
        product: VecturaKit
      - package: VecturaKit
        product: VecturaNLKit
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon

  # UI Framework
  UI:
    type: framework
    platform: macOS
    sources:
      - path: Sources/UI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.balakumar.engram.ui
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - target: AudioEngine
      - target: Intelligence
      - target: Database

  # Main Application
  Engram:
    type: application
    platform: macOS
    sources:
      - path: Sources/App
    resources:
      - path: Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.balakumar.engram
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Engram.entitlements
    dependencies:
      - target: AudioEngine
        embed: true
      - target: Database
        embed: true
      - target: Intelligence
        embed: true
      - target: UI
        embed: true
    postBuildScripts:
      - name: Copy MLX Shaders
        script: |
          # Copy MLX Metal shaders bundle if it exists
          MLX_BUNDLE=$(find "${BUILD_DIR}/../../SourcePackages" -name "mlx-swift_Cmlx.bundle" -type d 2>/dev/null | head -1)
          if [ -n "$MLX_BUNDLE" ] && [ -d "$MLX_BUNDLE" ]; then
            mkdir -p "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Resources/"
            cp -R "$MLX_BUNDLE" "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Resources/" 2>/dev/null || true
            echo "Copied MLX shaders from $MLX_BUNDLE"
          fi

  # Test Target
  EngramTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/EngramTests
    dependencies:
      - target: AudioEngine
      - target: Database
      - target: Intelligence

schemes:
  Engram:
    build:
      targets:
        Engram: all
        AudioEngine: [build, test, analyze]
        Database: [build, test, analyze]
        Intelligence: [build, test, analyze]
        UI: [build, test, analyze]
    run:
      config: Debug
      executable: Engram
    test:
      config: Debug
      targets:
        - EngramTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
